### ISSUE TITLE
[Conflict issue] LethalCompanyVariables incompatible

### ISSUE THREAD

**Issue by CoolLKKPS** [DaXcess/LCVR#233] opened 2024-04-17 20:46 UTC
2 patch released and i still get this error:

[20:26:06.0471797] [Info   :   BepInEx] Loading [LCVR 1.2.2]
[20:26:15.0794532] [Error  : Unity Log] ArgumentException: Path is empty
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) (at <787acc3c9a4c471ba7d971300105af24>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
System.IO.File.ReadAllBytes (System.String path) (at <787acc3c9a4c471ba7d971300105af24>:0)
LCVR.Plugin.VerifyGameVersion () (at <6cf3fc7227be4a9c8b5d368dc88b5f15>:0)
LCVR.Plugin.Awake () (at <6cf3fc7227be4a9c8b5d368dc88b5f15>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[20:26:15.0794532] [Error  : Unity Log] ArgumentException: Path is empty
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) (at <787acc3c9a4c471ba7d971300105af24>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
System.IO.File.ReadAllBytes (System.String path) (at <787acc3c9a4c471ba7d971300105af24>:0)
LCVR.Plugin.VerifyGameVersion () (at <6cf3fc7227be4a9c8b5d368dc88b5f15>:0)
LCVR.Plugin.Awake () (at <6cf3fc7227be4a9c8b5d368dc88b5f15>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by DaXcess** [comment] 2024-04-17 20:49
This means that `Assembly.Location` fails on the game assembly. This does not happen unless the game has been tampered with.

**Comment by CoolLKKPS** [comment] 2024-04-17 20:54
@DaXcess so u mean my game are corrupted, hmm weird, will try to re-install, but still just in case need to let u know, base game are updated at 16 april 2024 21:01:06 UTC

**Comment by CoolLKKPS** [comment] 2024-04-17 21:01
ok turns out somehow `BepInEx_Faster_Load_AssetBundles_Patcher v0.4.0 by DiFFoZ` still load old version of LC_VR, so this is a false issue, will close that

**Comment by CoolLKKPS** [comment] 2024-04-17 21:08
this getting really weird now, i have 2 mod profile, one got no problem, other will report error, still investigating

**Comment by CoolLKKPS** [comment] 2024-04-17 21:11
this mod conflict with LethalCompanyVariables v2.2.0 by AMRV, will send a issue ticket in there

**Comment by DaXcess** [comment] 2024-04-18 08:04
Confirmed that LCVR + LethalCompanyVariables breaks the assembly path. I have not yet taken a look at that mod but if it breaks this badly it must mean that they're using a patcher plugin since they can be used to completely change the way assemblies are loaded.

**Comment by DaXcess** [comment] 2024-04-18 10:11
Fixed in b5bc5a130548d9bf632f2c81d00df6f987ad245c

**Closed by DaXcess** 2024-04-18 10:11 UTC

**Comment by CoolLKKPS** [comment] 2024-04-18 10:21
i just waked up, nice!
