### ISSUE TITLE
Game seemingly starts on vr, when entering a game, it's stuck and beheaves like it's no longer on vr

### ISSUE THREAD

**Issue by Charmandrigo** [DaXcess/LCVR#206] opened 2024-02-16 02:02 UTC
this is what I see when I start a game:
![imagen](https://github.com/DaXcess/LCVR/assets/30424766/f538a7b8-9213-4832-bf96-41a9ee4553a2)

a black screen, that mesage saying to grab. on my HMD, the entire UI appears like it's on desktop for some reason.
I am able to control the game on the menus in vr perfectly, I see my controller pointers and all, I can't play the game and no idea why.
I have yippeemen pack too, no other mods disrupt this?
I have a Pimax 5k plus HMD

**Comment by panp0d** [comment] 2024-04-13 22:15
i have the same  in update 50

**Comment by DaXcess** [comment] 2024-04-16 13:10
Duplicate of #194

**Closed by DaXcess** 2024-04-16 13:10 UTC
