### ISSUE TITLE
Fails to move camera with player is ejected into space

### ISSUE THREAD

**Issue by EliAgne** [DaXcess/LCVR#221] opened 2024-03-13 02:31 UTC
When failing to meet quota, the player is ejected into space. While using this mod, the camera almost always fails to move with the player once ejected. I have seen this work once during 40+ hours of using this mod. 

I am using a steam index.

**Comment by DaXcess** [comment] 2024-03-18 13:46
Can't seem to reproduce this issue, so it's either caused by another mod, or has already been fixed on the `dev` branch (which is what I exclusively use). If it's the latter, then v1.2.0 will fix the issue.

**Closed** 2024-03-19 11:16 UTC

**Comment by EliAgne** [comment] 2024-03-25 00:05
Confirmed fixed by v1.2.0.
