### ISSUE TITLE
As the title suggests, I have been unable to figure out the button(s) to switch items in my hotbar.

### ISSUE THREAD

**Issue by AlexPayn3** [DaXcess/LCVR#142] opened 2024-01-17 22:29 UTC
As the title suggests, I have been unable to figure out the button(s) to switch items in my hotbar. It's randomly switched a few times but I have been unable to replicate the action.

**Comment by DaXcess** [comment] 2024-01-18 09:51
Duplicate of #140

**Closed by DaXcess** 2024-01-18 09:51 UTC
