### ISSUE TITLE
Blue borders at the edges of the screen

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#167] opened 2024-01-22 11:05 UTC
So I did a little digging, and it turns out that (at least according to internet) this is caused by an occlusion mask. I've tried searching for ways to change the size of this mask (or disable it outright) but could not find anything about this. I also don't know if this is something to be changed by Unity or OpenXR (though when testing with NVidia NSight, it seems that it is being rendered by Unity).

Any help or input is much appreciated!

**Comment by DaXcess** [comment] 2024-01-22 11:09
Also to clarify: The fact that the blue edges are there **is** normal. The fact that according to a group of people that on some headsets this edge is **always** visible **is not** normal (I think).

**Comment by matejdro** [comment] 2024-01-22 12:44
Dupe of https://github.com/DaXcess/LCVR/issues/96?

**Closed** 2024-01-22 18:59 UTC
Labels: bug
